---
title: "C2.TCR.integration"
author: "Nick Borcherding"
date: "10/27/2020"
output: html_document
---
```{r}
library(scRepertoire)
source("./R/functions.R")
setwd("~/Documents/GitHub/lg_dataAnalysis")

colorblind_vector <- colorRampPalette(c("#FF4B20", "#FFB433", "#C6FDEC", "#7AC5FF", "#0348A6"))
```


```{r}
###################################
#Load Data
##################################
file_list <- list.files("./data/")
file_list <- file_list <- file_list[!grepl(".rda|.rds", file_list)]

contig_list <- list()
for (i in seq_along(file_list)){
    contig_list[[i]] <- read.csv(paste0("./data/", file_list[i], "/filtered_contig_annotations.csv"))
}

names(contig_list) <- file_list

###Need to remove prefixes of these samples that were added previously
for (i in c(4,5,6, 13,14,15)) {
    contig_list[[i]]$barcode <- substr(contig_list[[i]]$barcode, 11, 28)
}
```


```{r}
###################################
#Combine Contigs
###################################
combined <- combineTCR(contig_list, samples = file_list, ID = rep("1", 15), cells = c("T-AB"), filterMulti = T, removeNA = T)

for (i in seq_along(combined)) {
    combined[[i]]$barcode <- gsub(names(combined)[i], file_list[i], combined[[i]]$barcode)
}

combined <- addVariable(combined, "Patient", c("Pt1", "Pt2", "Pt3", "Pt4", "Pt5", "Pt6", "Pt1", "Pt2", "Pt3", "Pt1", "Pt2", "Pt3", "Pt4", "Pt5", "Pt6"))
```

* Check AA motifs for position along cdr3 - i.e. what is 10x Cell Ranger providing?
* bootstrap comparison of LV of random TCR in plasma healthy to results, take lowest global similarity and compare
    * filter is just < 2 efit distance
* bootstrap comparison of motif results of random TCR in plasma healthy to results
    * filter <- enrichment in group vs comparison > 10-fold
    * filter <- probability < 0.001
* additional filter with checkVgenes
    
```{r}
calculateConvergence <- function(combined, chain = "TCRB", group = NULL, 
                          motif.length = 3, num.cores =2, boot.straps = 1000, 
                          p.value.motif = 0.001, fc.motif = 5) {
  tmp.list <- parsingContigList(combined, group = group)
  load("./data/pbmcControls.rda")
  controls <- getTCR(pbmc, "TCRB")
  
  for (x in seq_along(tmp.list)) {
    le <- x
    tmp <- tmp.list[[x]]
    TCR <- getTCR(tmp, chain)
    message(paste("Calculating Global Convergence in:", names(tmp.list)[x]))
    positions_LV <- globalConvergence(tmp, chain = chain)
    positions_LV <- checkVgenes(positions_LV, TCR)
    message(paste("Calculating Local Convergence in:", names(tmp.list)[x]))
    positions_motif <- localConvergence(tmp, chain = chain, motif.length=motif.length)
    
    message(paste("Bootstrapping Random Global Convergence in:", names(tmp.list)[x]))
    bootstrap_gc <- pbmclapply(1:boot.straps, sampleControl_gc, mc.cores = num.cores)
    message(paste("Bootstrapping Random Local Convergence in:", names(tmp.list)[x]))
    bootstrap_lc <- pbmclapply(1:boot.straps, sampleControl_lc, mc.cores = num.cores)
    
    message(paste("Filtering Bootstrapped Local Convergence in:", names(tmp.list)[x]))
    #Make single data frame of motifs in bootstrap values
    x <- lapply(bootstrap_lc, function(x){data.frame(x)})
    df <- suppressWarnings(Reduce(function(x, y) merge(x=x, y=y, by="Var1", all.x=T, all.y=T), x))
    df[is.na(df)] <- 0

    ##for each motif, calculate p-value and fold-change
    table <- as.data.frame(table(positions_motif$spec.Motif))

    for (i in seq_len(nrow(table))) {
      vector <- df[table[,"Var1"][i], 2:ncol(df)]
      number <- table[i,"Freq"]
      table$p[i] <- length(vector[vector >= number])/length(vector)
      table$fc[i] <- number/median(as.numeric(vector))
    }
    #Filter out motifs based on p-value and fold-change
    table <- table[table$p <= p.value.motif & table$fc >= fc.motif,]
    positions_motif <- positions_motif[positions_motif$spec.Motif %in% table$Var1,]
    edges <- rbind.data.frame(positions_LV, positions_motif[,c(1,2,4)])
    vertices <- unique(as.data.frame(TCR$Var1))
    
    g = graph_from_data_frame(edges, directed = FALSE, vertices = vertices)

    clusters <- components(g, mode = "strong")
    membership <- data.frame(cdr3 = names(clusters$membership), TCRcluster = clusters$membership)
    membership$TCRcluster <- paste0(names(tmp.list)[le], "_", membership$TCRcluster)
    membership <- merge(membership, TCR, by.x = "cdr3", by.y = "Var1")
    
    motifs <- positions_motif %>% 
        group_by(To) %>% 
        summarise(filtered.motifs = paste(unique(spec.Motif), collapse = ','))
    membership <- merge(membership, motifs, by.x = "cdr3", by.y = "To")
    tmp <- merge(tmp, membership, by.x = chainCheck(chain)[[1]], by.y = "cdr3")
    tmp.list[[le]] <- tmp
  }
  return(tmp.list)
}

testRun <- calculateConvergence(combined, chain = "TCRB", group = "Patient", 
                          motif.length = 3, num.cores =3, boot.straps = 1000, 
                          p.value.motif = 0.001, fc.motif = 5)
```

```{r}
data <- data.frame(foo=c(1, 1, 2, 3, 3, 3), bar=c('a', 'b', 'a', 'b', 'c', 'd'),
stringsAsFactors = FALSE)

library("dplyr")
library(purrr)
p <- function(v) {
  Reduce(f=paste, x = v)
 }



motifs <- positions_motif %>% 
  group_by(To) %>% 
  mutate(filtered_motifs=p(spec.Motif))


```

```{r}
library(stringr)
library(stringdist)
library(parallel)
library(pbmcapply)



tmp <- combined[[15]]
TCR <- getTCR(tmp, "TCRB")
positions_LV <- globalConvergence(tmp, chain = "TCRB")
positions_LV <- checkVgenes(positions_LV, TCR)
positions_motif <- localConvergence(tmp, chain = "TCRB", motif.length=3)


load("./data/pbmcControls.rda")
controls <- getTCR(pbmc, "TCRB")

##################################################
##Will error without chain saved to the environment
#################################################

bootstrap_gc <- pbmclapply(1:1000, sampleControl_gc, mc.cores = 3)
bootstrap_lc <- pbmclapply(1:1000, sampleControl_lc, mc.cores = 3)

#Make single data frame of motifs in bootstrap values
x <- lapply(bootstrap_lc, function(x){data.frame(x)})
df <- Reduce(function(x, y) merge(x=x, y=y, by="Var1", all.x=T, all.y=T), x)
df[is.na(df)] <- 0

##for each motif, calculate p-value and fold-change
table <- as.data.frame(table(positions_motif$spec.Motif))

for (i in seq_len(nrow(table))) {
  vector <- df[table[,"Var1"][i], 2:ncol(df)]
  number <- table[i,"Freq"]
  table$p[i] <- length(vector[vector >= number])/length(vector)
  table$fc[i] <- number/median(as.numeric(vector))
}
#Filter out motifs based on p-value and fold-change
table <- table[table$p <= 0.001 & table$fc > 5,]
positions_motif <- positions_motif[positions_motif$spec.Motif %in% table$Var1,]
```


```{r}
library(ggraph)
library(igraph)

edges <- rbind.data.frame(positions_LV, positions_motif[,c(1,2,4)])
edges <- checkVgenes(edges, TCR)
vertices <- unique(as.data.frame(TCR$Var1))



g = graph_from_data_frame(edges, directed = FALSE, vertices = vertices)
lou <- components(g, mode = "weak")
test <- as.data.frame(table(lou$membership))

clusters <- components(g, mode = "strong")
membership <- data.frame(cdr3 = names(clusters$membership), TCRcluster = clusters$membership)
membership$TCRcluster <- paste0(names(tmp.list)[x], "_", membership$TCRcluster)

plot(g, vertex.label = NA, vertex.color=rainbow(46, alpha=0.6)[lou$membership])
```

```{r}
ggraph(g) +
  geom_edge_link(show.legend = FALSE, aes(color = "Type")) +
  geom_node_point()  +
  theme_graph()

plot
```